language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project haifahrul-mws — token 1/LQ2VIR-kKO9n7LLZ_7QrAQ-rxsfw7IBsXl1Gvxh_3UI
